name: docs

on: 
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    container: python:3.8
    name: Build documentation and deploy on gh-pages

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build document with Sphinx
      run: bash docs/build_docs.sh
        
    - name: Deploy to GitHub pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.DOC_DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html