name: Testing
on: [push]

jobs:
  example_tests:
    name: Example tests
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: pip install .
      # rsync is needed for the subsequently used action
      - run: apt update && apt install -y ffmpeg rsync
      - run: for f in examples/*.py; do python "$f"; done
      # This action will only update the examples-material branch if it
      # is affected by the changes that triggered the job
      - name: Upload examples-material
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: examples-material
          FOLDER: plots
